name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: [release]
    if: needs.release.outputs.new_release == 'true' #
    steps:
      - name: build step
        run: echo build cmd
  deploy:
    runs-on: ubuntu-latest
    needs: [build, release]
    steps:
      - name: Deploy step
        run: |
          echo deploy ${{ needs.release.outputs.new_release_version }}
          echo IMAGE_TAG=${{ needs.release.outputs.new_release_version }} >> $GITHUB_ENV 
          
      - name: verify step
        run: |
          echo from job: ${{ needs.release.outputs.new_release }}
          echo from jobver: ${{ needs.release.outputs.new_release_version }}
          echo from var: $IMAGE_TAG
          echo from env: ${{ env.IMAGE_TAG }}
  verify:
    runs-on: ubuntu-latest
    needs: [deploy, release]
    steps:
      - name: verify
        run: |
          echo from release job: ${{ needs.release.outputs.new_release }}
          echo from release job new version: ${{ needs.release.outputs.new_release_version }}
      - name: script
        run: bash deployment/verify.sh
        env:
          IMAGE_TAG: ${{ needs.release.outputs.new_release_version }}

