name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: [release]
    if: needs.release.outputs.new_release == 'true' #
    steps:
      - name: Deploy step
        run: echo deploy cmd
