name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: [release]
    # if: needs.release.outputs.new_release == 'true'
    steps:
      - name: Checkout
        run: echo ${{ needs.release.outputs }}
      - name: Deploy step
        run: echo deploy cmd
